import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"


export default function Home() {
  const {data: session} = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid">
        <div className="row">
            <div className="col-lg-4">

              <div className="card m-5">
                <div className="card-body">
                  <h5 className="card-title text-center">Join Lobby</h5>

                  <form action="/api/join" method="post">
                    <div className="form-group">
                      <label htmlFor="code">Code</label>
                      <input type="text" className="form-control" id="code" name="code" placeholder="1234" pattern="\d{4}" required />
                      <small id="code" className="form-text text-muted">4 nubmers only</small>
                    </div>
                    
                    <button type="submit" className="btn btn-primary">Submit</button>
                  </form>
                </div>
              </div>

            </div>
            <div className="col-lg-8">
                Container Right
            </div>
        </div>
      </div>

    </>

  );
}

