import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Game from './sketch'


import { useRouter } from 'next/router'
import { useState } from 'react'


export default function Home() {
    const { data: session } = useSession()
    const router = useRouter()
    const [code, setCode] = useState("")

    const handleSubmit = (e) => {
        e.preventDefault()
        router.push(`/lobby/?code=${code}`)
    }

    return (
        <>
            <Head>
                <title>Help | Ricochet Robots</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="px-4 py-5 my-5 text-center">
                <h1 className="display-5 fw-bold"> Help</h1>
                <div className="col-lg-6 mx-auto w-25">
                    <p className="lead mb-2"><b>Ricochet Robots Regler</b></p>
                    <p className="">Spillet gælder om at føre en vilkårlig robot (brik) hen til et ensfarvet felt, som er tilfældigt placeret. <br/>Personen der kan gøre dette på færest træk vinder</p>
                    <p className="">Robotterne kan gå i alle retninger, men har man først valgt en retning, går man indtil man støder på en væg, hvorefter der er blevet taget et træk. <bt/> Derudover er det ikke muligt at gå igennem de andre robotter</p>
                    <p className="">Under spillet sidder alle spillerne og kigger på pladen, og når man så får en løsning byder man på en løsning, og når tiden er gået, vil den spiller med færrest antal træk vise sin løsning. Er denne løsning forkert vil spilleren få et minus point</p>
                    <p className=""></p>
                </div>
            </div>
        </>

    );
}



