import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Game from './sketch'


export default function Home() {
  const {data: session} = useSession()

  return (
    <>
      <Head>
        <title>Ricochet Robots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session ? (

        <div className="px-4 py-5 my-5 text-center">
          <h1 className="display-5 fw-bold"> Ricochet Robots</h1>
          <div className="col-lg-6 mx-auto">
            <p className="lead mb-4">A game for the mind</p>
            <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
              <button type="button" className="btn btn-primary btn-lg px-4 gap-3" onClick={signIn}>Sign in</button>
            </div>
          </div>
        </div>


      ) : (
        <div className="container-fluid">
          <div className="row">
              <div className="col-lg-4">

                <div className="card m-5">
                  <div className="card-body">
                    <h5 className="card-title text-center">Join Lobby</h5>

                    <form action="/api/lobby/join" method="post">
                      <div className="form-group">
                        <label htmlFor="code">Code</label>
                        <input type="text" className="form-control" id="code" name="code" placeholder="1234" pattern="\d{4}" required />
                        <small id="code" className="form-text text-muted">4 numbers only</small>
                      </div>
                      
                      <button type="submit" className="btn btn-primary">Submit</button>
                    </form>
                    <a href="#" className="link-primary">Create lobby instead</a>
                  </div>
                </div>

              </div>
              <div className="col-lg-8">
                  OGABOGA
              </div>
          </div>
        </div>

      )}
    </>

  );
}



